# theme.toml template for a Hugo theme

name = "Learn Crafting Software"
license = "MIT"
licenselink = "https://github.com/vantagedesign/ace-documentation/blob/master/LICENSE.md"
description = "A documentation theme featuring a clean design, code highlighting and useful shortcodes for writing your project documentation."
homepage = "https://github.com/vantagedesign/ace-documentation"
tags = ["software", "engineering", "team", "gitflow"]
features = ["schedule", "projects", "assignments", "quiz"]
min_version = "0.51.0"

[author]
  name = "Janyl Jumadinova"
  homepage = "https://janyljumadinova.com"
